export const serveList = (data, message) => $HTTP.post('serveList', data, message)
export const product = (data, message) => $HTTP.post('product', data, message)
export const productDetail = (data, message) => $HTTP.post('productDetail', data, message)
export const addCart = (data, message) => $HTTP.post('addCart', data, message)
export const getcartList = (data, message) => $HTTP.post('cartList', data, message)
